package com.app.cook_diary.entity;

import java.util.Date;

public class Dish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.user_id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.name
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.preparation_time
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private Integer preparationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.cost
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.image_url
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.material
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.recipe
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private String recipe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.created_at
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.id
     *
     * @return the value of dish.id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.id
     *
     * @param id the value for dish.id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.user_id
     *
     * @return the value of dish.user_id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.user_id
     *
     * @param userId the value for dish.user_id
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.name
     *
     * @return the value of dish.name
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.name
     *
     * @param name the value for dish.name
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.preparation_time
     *
     * @return the value of dish.preparation_time
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public Integer getPreparationTime() {
        return preparationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.preparation_time
     *
     * @param preparationTime the value for dish.preparation_time
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setPreparationTime(Integer preparationTime) {
        this.preparationTime = preparationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.cost
     *
     * @return the value of dish.cost
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.cost
     *
     * @param cost the value for dish.cost
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.image_url
     *
     * @return the value of dish.image_url
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.image_url
     *
     * @param imageUrl the value for dish.image_url
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.material
     *
     * @return the value of dish.material
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.material
     *
     * @param material the value for dish.material
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.recipe
     *
     * @return the value of dish.recipe
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public String getRecipe() {
        return recipe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.recipe
     *
     * @param recipe the value for dish.recipe
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setRecipe(String recipe) {
        this.recipe = recipe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.created_at
     *
     * @return the value of dish.created_at
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.created_at
     *
     * @param createdAt the value for dish.created_at
     *
     * @mbg.generated Tue Dec 31 00:51:58 JST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}